# Options for analysis running.
run:
  concurrency: 4
  timeout: 5m
  go: '1.19'

# output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  format: colored-line-number
  # Print lines of code with issue.
  # Default: true
  print-issued-lines: true
  # Print linter name in the end of issue text.
  # Default: true
  print-linter-name: true
  # Make issues output unique by line.
  # Default: true
  uniq-by-line: true
  # Add a prefix to the output file references.
  # Default is no prefix.
  path-prefix: ""
  # Sort results by: filepath, line and column.
  sort-results: false

linters:
  enable:
#    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - goheader
    - goimports
#    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
#    - gosec
    - gosimple
    - govet
  disable:
    - containedctx
    - contextcheck
