definitions:
  domain.Order:
    properties:
      country:
        type: string
      item_type:
        type: string
      order_date:
        type: string
      order_id:
        type: integer
      order_priority:
        type: string
      region:
        type: string
      sales_channel:
        type: string
      ship_date:
        type: string
      total_cost:
        type: number
      total_profit:
        type: number
      total_revenue:
        type: number
      unit_cost:
        type: number
      unit_price:
        type: number
      units_sold:
        type: integer
    type: object
  handler.ListOrdersRes:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Order'
        type: array
    type: object
  handler.Req:
    description: Request body
    properties:
      id:
        type: string
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: health check
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Readiness Probe
      tags:
      - health
  /list:
    get:
      consumes:
      - application/json
      description: reflect back the request body
      parameters:
      - description: Order Type
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListOrdersRes'
      summary: listOrders Route
      tags:
      - list
  /reflect:
    post:
      consumes:
      - application/json
      description: reflect back the request body
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.Req'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Req'
      summary: reflectReq Route
      tags:
      - reflect
swagger: "2.0"
