info:
  contact: {}
paths:
  /:
    get:
      description: health check
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Readiness Probe
      tags:
      - health
swagger: "2.0"
